---
title       : RNA-seq Vis Report
subtitle    : 
author      : 
job         : 
framework   : revealjs        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
revealjs:
  theme: solarized
  transition: none
  center: "true"
hitheme     : simple     # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

<style type="text/css">
body {background:none transparent;
}
</style>

<script language="javascript" type="text/javascript">
  function resizeIframe(obj) {
    obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
  }
</script>

# RNA-seq Vis report
<small> Created by [RNA-seq Vis team](https://yuanhangliu.shinyapps.io/RNA-seq)</small>

---

## Data table

```{r results = 'asis', comment = NA, cache = F, message=FALSE, warning=FALSE, echo=FALSE}
cat('<iframe src="htmlFiles/datatable.html" width=1000px height=1000px allowtransparency="true"> </iframe>')
```

---

## Density plot
```{r results = 'asis', comment = NA, cache = F, message=FALSE, warning=FALSE, echo=FALSE}
cat('<iframe src="htmlFiles/density.html" width=1000px height=1000px allowtransparency="true"> </iframe>')
```

---

## Scatter plot

```{r echo=FALSE, warning=FALSE,cache=FALSE,results='asis'}
cat('<iframe src="htmlFiles/Scatterplot.html" width=1000px height=1000px allowtransparency="true"> </iframe>')
```

---

## Box plot

```{r echo=FALSE, warning=FALSE,cache=FALSE,results='asis'}
cat('<iframe src="htmlFiles/Boxplot.html" width=1000px height=1000px allowtransparency="true"> </iframe>')
```

---

## Principal component

```{r echo=FALSE, warning=FALSE,cache=FALSE,results='asis'}
cat('<iframe src="htmlFiles/pcaplot.html" width=1000px height=1000px allowtransparency="true"> </iframe>')
```

---

## Gene-gene interaction

```{r echo=FALSE, warning=FALSE,cache=FALSE,results='asis'}
cat('<iframe src="htmlFiles/forceNet.html" width=1000px height=1000px allowtransparency="true"> </iframe>')
```

---

## DE data table

```{r echo=FALSE, warning=FALSE,cache=FALSE,results='asis'}
cat('<iframe src="htmlFiles/DEdatatable.html" width=1000px height=1000px allowtransparency="true"> </iframe>')
```

---

## MA plot

```{r echo=FALSE, warning=FALSE,cache=FALSE,results='asis'}
cat('<iframe src="htmlFiles/MAplot.html" width=1000px height=1000px allowtransparency="true"> </iframe>')
```

